const questions = [
  {question:"Evaluate the following Python arithmetic expression: (3*(1+2)**2 - (2**2)*3). What is the result?",options:["3","13","15","69"],correct:2,explanation:"(1+2)=3, 3**2=9, 3*9=27. Then (2**2)=4, 4*3=12. Finally 27-12=15."},
  {question:"You must write a script that asks the user for a value. The value must be used as a whole number in a calculation, even if the user enters a decimal value. Which code segment should you use?",options:['totalItems = int(input("How many items would you like?"))','totalItems = str(input("How many items would you like?"))','totalItems = float(input("How many items would you like?"))','totalItems = input("How many items would you like?")'],correct:0,explanation:"int() converts the input string to a whole number (integer), truncating any decimal portion to meet the requirement."},
  {question:"You need to calculate years of service and print a congratulatory message. Which code should you use at line 03?",code:"01 start = input(\"How old were you on your start date?\")\n02 end = input(\"How old are you today?\")\n03 ???",options:['print("congratulations on " + int(end - start) + " years of service!")','print("congratulations on " + (int(end) - int(start)) + " years of service!")','print("congratulations on " + str(end - start) + " years of service!")','print("congratulations on " + str(int(end) - int(start)) + " years of service!")'],correct:3,explanation:"input() returns strings, so you must convert to int for subtraction, then str() for concatenation. str(int(end)-int(start)) handles both."},
  {question:"You want to add notes to your code so other team members will understand it. What should you do?",options:["Place the notes after the last line of code separated by a blank line","Place the notes inside of parentheses on any line","Place the notes after the # sign on any line","Place the notes before the first line of code separated by a blank line"],correct:2,explanation:"In Python, the # symbol marks the start of a comment. Everything after # on that line is ignored by the interpreter."},
  {question:"You are writing an application that uses the sqrt function. The program must reference the function using the name squareRoot. Which code segment should you use?",options:["from math import sqrt as squareRoot","from math.sqrt as squareRoot","import math.sqrt as squareRoot","import sqrt from math as squareRoot"],correct:0,explanation:"The correct Python syntax for importing with an alias is 'from module import function as alias'. Only option A uses valid syntax."},
  {question:"The out.txt file does not exist. You run the code. The statement says: 'The code will execute without error.' Is this correct?",code:"import sys\ntry:\n    file_in = open(\"in.txt\", 'r')\n    file_out = open(\"out.txt\", 'w+')\nexcept IOError:\n    print('cannot open', file_name)\nelse:\n    i = 1\n    for line in file_in:\n        print(line.rstrip())\n        file_out.write(\"line \" + str(i) + \": \" + line)\n        i = i + 1\n    file_in.close()\n    file_out.close()",options:["No change is needed (correct as stated)","The code runs, but generates a logic error","The code will generate a runtime error","The code will generate a syntax error"],correct:0,explanation:"'w+' mode creates the file if it doesn't exist and opens it for reading/writing. The code executes without error."},
  {question:"You are reading a file line by line. If a blank line is encountered it must be ignored. When all lines have been read the file must close. Which code for lines 05 and 06?",code:"01 inventory = open(\"inventory.txt\", 'r')\n02 eof = False\n03 while eof == False:\n04     line = inventory.readline()\n05     ???\n06         ???\n07             print(line)\n08     else:\n09         print(\"End of file\")\n10         eof = True\n11     inventory.close()",options:["05 if line != '':\\n06  if line !=\"\":","05 if line != '\\n':\\n06  if line != None:","05 if line != '\\n':\\n06  if line != \"\":","05 if line != '':\\n06  if line != \"\\n\":"],correct:3,explanation:"readline() returns '' at EOF (line 05 checks this) and '\\n' for blank lines (line 06 skips these). Option D correctly handles both cases."},
  {question:"The Happy Clown code has errors. Which error exists in the code?",code:"01 import math\n02 #default motion for happy clown\n03 power = True\n04 move = 0\n05 while(power):\n06     if move == 0:\n07         turnValue = math.pi/move\n08         move+=5\n09     else:\n10         turnValue = 0\n11         move = 0",options:["Line 05 syntax error: should read (power == True)","Line 08 syntax error: += is invalid","Line 07 causes a runtime error due to division by zero","Line 05 runtime error: expression is incomplete"],correct:2,explanation:"Since move=0 and the if condition is move==0, the code executes math.pi/0 which causes a ZeroDivisionError at runtime."},
  {question:"Woodgrove Bank is migrating code to Python. Which documentation syntax is correct?",options:["# comment\\ndef get_balance():\\n  return balance","def get_balance():\\n  /*comment*/\\n  return balance","//comment\\ndef get_balance():\\n  return balance","def get_balance():\\n  #comment\\n  return balance"],correct:3,explanation:"Python uses # for inline comments inside functions. /* */ and // are C/Java syntax and invalid in Python."},
  {question:"You need to accept input from the user and print it. Which code should you write at line 02?",code:"01 print(\"What is your name?\")\n02 ???\n03 print(name)",options:["name = input","input(name)","name = input()","input(\"name\")"],correct:2,explanation:"input() is a function call that pauses for user input and returns the typed value as a string. Assigning to name stores it."},
  {question:"You need to read and write data to a text file. If the file does not exist it must be created. If it has content the content must be removed. Which code?",options:['open("local_data", "r+")','open("local_data", "w+")','open("local_data", "r")','open("local_data", "w")'],correct:1,explanation:"'w+' opens for reading and writing, creates the file if missing, and truncates existing content. It meets all three requirements."},
  {question:"What is the output of this code?",code:"numList = [0,1,2,3,4]\nprint(5 in numList)",options:["4","False","True","5"],correct:1,explanation:"The 'in' operator checks membership. 5 is not in [0,1,2,3,4], so the result is False."},
  {question:"What is the output printed to the screen?",code:"x = 4\nwhile x >= 1:\n    if x % 4 == 0:\n        print(\"party\")\n    elif x - 2 < 0:\n        print(\"cake\")\n    elif x / 3 == 0:\n        print(\"greeting\")\n    else:\n        print(\"birthday\")\n    x = x - 1",options:["birthday, party, greeting, cake","party, birthday, birthday, cake","party, greeting, birthday, cake","birthday, greeting, party, cake"],correct:1,explanation:"x=4: 4%4==0→party. x=3: none match first two, 3/3=1≠0→else→birthday. x=2: same→birthday. x=1: 1-2<0→cake."},
  {question:"What is the output value?",code:"list_1 = [1, 2]\nlist_2 = [3, 4]\nlist_3 = list_1 + list_2\nlist_4 = list_3 * 3\nprint(list_4)",options:["[3, 6, 9, 12]","[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]","[[1,2],[3,4],[1,2],[3,4],[1,2],[3,4]]","[[1,2,3,4],[1,2,3,4],[1,2,3,4]]"],correct:1,explanation:"+ concatenates lists: [1,2,3,4]. Multiplying by 3 repeats elements: [1,2,3,4,1,2,3,4,1,2,3,4]."},
  {question:"Minors and seniors must receive a 10% discount. Which code should you add on line 03?",code:"01 def get_discount(minor, senior):\n02     discount = .1\n03     ???\n04         discount = 0\n05     return discount",options:["if not (minor and senior):","if not (minor or senior):","if (not minor) and senior:","if (not minor) or senior:"],correct:0,explanation:"'if not (minor and senior)' evaluates to True when the person is not eligible (not both minor and senior), setting discount to 0."},
  {question:"A list named colors contains 200 colors. You need to slice the list to display every other color starting with the second color. Which code?",options:["colors[1:2]","colors[::2]","colors[2:2]","colors[1::2]"],correct:3,explanation:"colors[1::2] starts at index 1 (the second element) and steps by 2, giving every other color from the second onward."},
  {question:"What is the output of this code?",code:"import datetime\nd = datetime.datetime(2017, 4, 7)\nprint('{:%B-%d-%y}'.format(d))\nnum=1234567.890\nprint('{:,.4f}'.format(num))",options:["2017--April--07\\n1,234,567.890","Apr--07--2017\\n1,234,567,8900","April-07-17\\n1,234,567.8900","April--07--17\\n1234567.89"],correct:2,explanation:"%B=full month(April), %d=day(07), %y=2-digit year(17). {:,.4f} formats with commas and 4 decimal places giving 1,234,567.8900."},
  {question:"Which part of the expression is evaluated first?",code:"def main(a,b,c,d):\n    value = a+b*c-d\n    return value",options:["a+b","b*c","c-d"],correct:1,explanation:"Python follows standard operator precedence: multiplication (*) is evaluated before addition (+) and subtraction (-). So b*c is first."},
  {question:"Which operation is evaluated second?",code:"def main(a,b,c,d):\n    value = a+b*c-d\n    return value",options:["addition","subtraction"],correct:0,explanation:"After b*c, addition and subtraction are evaluated left to right. So a+(result of b*c) happens next, then subtraction."},
  {question:"Which expression is equivalent to the expression in the function?",code:"def main(a,b,c,d):\n    value = a+b*c-d\n    return value",options:["(a+b) * (c-d)","(a + (b*c)) - d","a + ((b*c) - d)"],correct:1,explanation:"Due to precedence, b*c happens first, then a is added, then d is subtracted. This matches (a+(b*c))-d."},
  {question:"Which two data types are stored in the rooms dictionary at line 01?",code:"01 rooms = {1: 'Foyer', 2: 'conference Room'}\n02 room = input('Enter the room number: ')\n03 if not room in rooms:\n04     print('Room does not exist.')\n05 else:\n06     print(\"The room name is \" + rooms[room])",options:["bool and string","float and bool","int and string","float and int"],correct:2,explanation:"The dictionary keys are integers (1,2) and the values are strings ('Foyer','conference Room'). So it stores int and string."},
  {question:"What is the data type of room at line 02?",code:"01 rooms = {1: 'Foyer', 2: 'conference Room'}\n02 room = input('Enter the room number: ')\n03 if not room in rooms:\n04     print('Room does not exist.')\n05 else:\n06     print(\"The room name is \" + rooms[room])",options:["bool","float","int","string"],correct:3,explanation:"input() always returns a string in Python 3, regardless of what the user types. So room is a string."},
  {question:"Why does line 03 fail to find the rooms when user enters '1'?",code:"01 rooms = {1: 'Foyer', 2: 'conference Room'}\n02 room = input('Enter the room number: ')\n03 if not room in rooms:\n04     print('Room does not exist.')\n05 else:\n06     print(\"The room name is \" + rooms[room])",options:["Invalid syntax","Mismatched data type(s)","Misnamed variable(s)"],correct:1,explanation:"The dictionary keys are integers but input() returns a string. Comparing string '1' to integer key 1 fails due to type mismatch."},
  {question:"Line 03 has: while (index < 10) — missing colon. Which code fixes line 03?",code:"01 numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n02 index = 0\n03 while (index < 10)\n04     print(numbers[index])\n05\n06     if numbers(index) = 6\n07         break\n08     else:\n09         index += 1",options:["while(index < 10):","while[index < 10]","while(index < 5):","while[index < 5]"],correct:0,explanation:"Python while loops require a colon at the end. while(index < 10): is the correct syntax with proper parentheses and colon."},
  {question:"Line 06 has: if numbers(index) = 6 — wrong brackets and operator. Which code fixes line 06?",code:"01 numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n02 index = 0\n03 while (index < 10)\n04     print(numbers[index])\n05\n06     if numbers(index) = 6\n07         break\n08     else:\n09         index += 1",options:["if numbers[index] == 6","if numbers[index] == 6:","if numbers(index) == 6","if numbers(index) == 6:"],correct:1,explanation:"Lists use square brackets [] for indexing, and comparison uses ==. The colon is required for the if statement. So: if numbers[index] == 6:"},
  {question:"What data type is age in line 01?",code:"01 age = input(\"Enter your age: \")\n02 year = input(\"Enter the four digit year: \")\n03 born = eval(year) - eval(age)\n04 message = \"You were born in \" + str(born)\n05 print(message)",options:["int","str","float","bool"],correct:1,explanation:"input() in Python 3 always returns a string. Even if the user types a number, it's stored as a str until explicitly converted."},
  {question:"What data type is born in line 03?",code:"01 age = input(\"Enter your age: \")\n02 year = input(\"Enter the four digit year: \")\n03 born = eval(year) - eval(age)\n04 message = \"You were born in \" + str(born)\n05 print(message)",options:["int","str","float","bool"],correct:0,explanation:"eval() evaluates the string as Python code. Whole number strings become int. int minus int equals int."},
  {question:"What data type is message in line 04?",code:"01 age = input(\"Enter your age: \")\n02 year = input(\"Enter the four digit year: \")\n03 born = eval(year) - eval(age)\n04 message = \"You were born in \" + str(born)\n05 print(message)",options:["int","str","float","bool"],correct:1,explanation:"Concatenating strings with + always produces a string. str(born) converts the int to str, then concatenation yields str."},
  {question:"What is displayed after the first print?",code:"a = 'Config'\nprint(a)\nb = a\na += 'config2'\nprint(a)\nprint(b)",options:["Config","Configconfig2","config2"],correct:0,explanation:"At the first print(a), variable a still holds 'Config'. The += operation happens afterward."},
  {question:"What is displayed after the second print(a)?",code:"a = 'Config'\nprint(a)\nb = a\na += 'config2'\nprint(a)\nprint(b)",options:["Config","Configconfig2","config2"],correct:1,explanation:"After a += 'config2', variable a becomes 'Config'+'config2' = 'Configconfig2'. Strings are immutable so this creates a new string."},
  {question:"What is displayed after print(b)?",code:"a = 'Config'\nprint(a)\nb = a\na += 'config2'\nprint(a)\nprint(b)",options:["Config","Configconfig2","config2"],correct:0,explanation:"b was assigned to a when a was 'Config'. Since strings are immutable, b still references the original 'Config' string."},
  {question:"What is printed at line 04?",code:"01 def checkType(value):\n02     dataType = type(value)\n03     return dataType\n04 print(checkType(True))\n05 print(checkType(1.0))\n06 print(checkType(1))\n07 print(checkType(\"True\"))",options:["<class 'bool'>","<class 'float'>","<class 'int'>","<class 'str'>"],correct:0,explanation:"True is a boolean literal in Python. type(True) returns <class 'bool'>."},
  {question:"What is printed at line 05?",code:"01 def checkType(value):\n02     dataType = type(value)\n03     return dataType\n04 print(checkType(True))\n05 print(checkType(1.0))\n06 print(checkType(1))\n07 print(checkType(\"True\"))",options:["<class 'bool'>","<class 'float'>","<class 'int'>","<class 'str'>"],correct:1,explanation:"1.0 has a decimal point, making it a float literal. type(1.0) returns <class 'float'>."},
  {question:"What is printed at line 06?",code:"01 def checkType(value):\n02     dataType = type(value)\n03     return dataType\n04 print(checkType(True))\n05 print(checkType(1.0))\n06 print(checkType(1))\n07 print(checkType(\"True\"))",options:["<class 'bool'>","<class 'float'>","<class 'int'>","<class 'str'>"],correct:2,explanation:"1 without a decimal point is an integer literal. type(1) returns <class 'int'>."},
  {question:"What is printed at line 07?",code:"01 def checkType(value):\n02     dataType = type(value)\n03     return dataType\n04 print(checkType(True))\n05 print(checkType(1.0))\n06 print(checkType(1))\n07 print(checkType(\"True\"))",options:["<class 'bool'>","<class 'float'>","<class 'int'>","<class 'str'>"],correct:3,explanation:"\"True\" is in quotes, making it a string literal, not a boolean. type(\"True\") returns <class 'str'>."},
  {question:"You need to generate a random float between 0.0 and 1.0. Which statement?",options:["random.randrange()","random.randrange(0.0, 1.0)","random.random()","random.randint(0, 1)"],correct:2,explanation:"random.random() returns a random float in [0.0, 1.0). randrange and randint work with integers only."},
  {question:"You use os.path.isfile(file) but get an error. What causes it?",code:"01 def read_file(file):\n02     line = None\n03     if os.path.isfile(file):\n04         data = open(file,'r')\n05         for line in data:\n06             print(line)",options:["The path method doesn't exist in os","The isfile method doesn't exist in path","You need to import the os library","isfile doesn't accept one parameter"],correct:2,explanation:"Without 'import os' at the top of the file, Python cannot resolve the os name, causing a NameError."},
  {question:"employees has 200 names, last 5 are management. To exclude management, which TWO slices work?",options:["employees[0:-4]","employees[1:-5]","employees[:-5]","employees[0:-5]","employees[1:-4]"],correct:[2,3],explanation:"employees[:-5] and employees[0:-5] are identical — both take all elements from the start up to but not including the last 5."},
  {question:"Which code defines get_name() for line 01? (function takes no parameters, asks for name inside)",options:["def get_name():","def get_name(biker):","def get_name(name):"],correct:0,explanation:"get_name() is called with no arguments on line 10, so it must be defined with no parameters. It uses input() inside."},
  {question:"Which code defines calc_calories() for line 04? (uses miles and calories_per_mile inside)",options:["def calc_calories():","def calc_calories(miles, burn_rate):","def calc_calories(miles, calories_per_mile):"],correct:2,explanation:"The function body uses 'miles' and 'calories_per_mile' as variables, so those must be the parameter names in the definition."},
  {question:"You need a random integer with min 5 and max 11. Which TWO functions work?",options:["random.randint(5, 11)","random.randrange(5, 12, 1)","random.randint(5, 12)","random.randrange(5, 11, 1)"],correct:[0,3],explanation:"randint(5,11) includes both endpoints (5-11). randrange(5,11,1) generates 5 through 10. Per the exam key, answers are A and D."},
  {question:"You need absolute value then remove decimals. Which TWO math functions?",options:["math.ceil(x)","math.fmod(x)","math.floor(x)","math.frexp(x)","math.fabs(x)"],correct:[2,4],explanation:"math.fabs(x) gets the absolute value. math.floor(x) removes decimals by rounding down to the nearest integer."},
  {question:"Average balance must truncate decimals. Which TWO code segments work?",options:["total_deposits**number_of_customers","total_deposits//number_of_customers","int(total_deposits/number_of_customers)","float(total_deposits//number_of_customers)"],correct:[1,2],explanation:"// (floor division) truncates decimals directly. int() also truncates the decimal portion of a division result."},
  {question:"Random number must be multiple of 5, lowest 5, highest 100. Which TWO work?",options:["from random import randrange\\nprint(randrange(5, 100, 5))","from random import randint\\nprint(randint(1, 20) * 5)","from random import randint\\nprint(randint(0, 20) * 5)","from random import randrange\\nprint(randrange(0, 100, 5))"],correct:[0,1],explanation:"randrange(5,100,5) gives multiples of 5 from 5-95. randint(1,20)*5 gives 5 to 100 in steps of 5. Both meet the requirements."},
  {question:"Code attempts to read file even if it doesn't exist due to indentation. Which THREE lines have indentation problems?",code:"01 import os\n02 def read_file(file):\n03     line = None\n04     if os.path.isfile(file):\n05         data = open(file,'r')\n06     while line != '':\n07         line = data.readline()\n08         print(line)",options:["Line 01","Line 02","Line 03","Line 04","Line 05","Line 06","Line 07","Line 08"],correct:[5,6,7],explanation:"Lines 06-08 (while loop and its body) should be indented inside the if os.path.isfile(file): block to only execute when the file exists."},
  {question:"Output must have strings in double-quotes, numbers without quotes, items separated by commas. Which THREE code segments work?",options:['print(\'\"{{0}}\",{{1}}\'.format(item, sales))','print(item + \",\" + sales)','print(\'\"\\"\' + item + \'\"\\",\' + sales)','print(\"{0},{1}\".format(item, sales))','print(\'\"\\"%s\", %s\' % (item, sales))'],correct:[0,2,4],explanation:"Options A, C, and E all properly enclose the item string in double-quotes while leaving the number unquoted with comma separation."},
  {question:"What does print(numList is alphaList) display?",code:"numList = [1,2,3,4,5]\nalphaList = [\"a\",\"b\",\"c\",\"d\",\"e\"]\nprint(numList is alphaList)\nprint(numList == alphaList)\nnumList = alphaList\nprint(numList is alphaList)\nprint(numList == alphaList)",options:["True (Yes)","False (No)"],correct:1,explanation:"'is' checks if two variables reference the same object. numList and alphaList are different objects, so the result is False."},
  {question:"What does print(numList == alphaList) display?",code:"numList = [1,2,3,4,5]\nalphaList = [\"a\",\"b\",\"c\",\"d\",\"e\"]\nprint(numList is alphaList)\nprint(numList == alphaList)\nnumList = alphaList\nprint(numList is alphaList)\nprint(numList == alphaList)",options:["True (Yes)","False (No)"],correct:1,explanation:"== checks value equality. [1,2,3,4,5] does not equal ['a','b','c','d','e'], so the result is False."},
  {question:"After numList = alphaList, what does print(numList is alphaList) display?",code:"numList = [1,2,3,4,5]\nalphaList = [\"a\",\"b\",\"c\",\"d\",\"e\"]\nprint(numList is alphaList)\nprint(numList == alphaList)\nnumList = alphaList\nprint(numList is alphaList)\nprint(numList == alphaList)",options:["True (Yes)","False (No)"],correct:0,explanation:"After assignment, both variables point to the same list object in memory. 'is' returns True because they are the same object."},
  {question:"x1='20', y1=3, a=x1*y1. Is the data type of variable 'a' str?",code:"# Code segment 1\nx1 = \"20\"\ny1 = 3\na = x1 * y1",options:["Yes","No"],correct:0,explanation:"Multiplying a string by an integer repeats the string. '20'*3 = '202020', which is still a string (str)."},
  {question:"x2=6, y2=4, b=x2/y2. Is the data type of variable 'b' float?",code:"# Code segment 2\nx2 = 6\ny2 = 4\nb = x2 / y2",options:["Yes","No"],correct:0,explanation:"In Python 3, the / operator always returns a float, even for integer operands. 6/4 = 1.5 which is float."},
  {question:"x3=2.5, y3=1, c=x3/y3. Is the data type of variable 'c' int?",code:"# Code segment 3\nx3 = 2.5\ny3 = 1\nc = x3 / y3",options:["Yes","No"],correct:1,explanation:"Dividing a float by an int returns a float. 2.5/1 = 2.5 which is float, not int."},
  {question:"Lines 01-04 start with #. Will they be ignored for syntax checking?",code:"01 # The calc_power function calculates exponents\n02 # x is the base\n03 # y is the exponent\n04 # The value of x raised to the y power is returned\n05 def calc_power(x, y):\n06     comment = \"#Return the value\"\n07     return x**y  # raise x to the y power",options:["Yes","No"],correct:0,explanation:"Lines starting with # are comments and are completely ignored by the Python interpreter during syntax checking and execution."},
  {question:"The # sign is optional for lines 02 and 03. True?",code:"01 # The calc_power function calculates exponents\n02 # x is the base\n03 # y is the exponent\n04 # The value of x raised to the y power is returned\n05 def calc_power(x, y):\n06     comment = \"#Return the value\"\n07     return x**y  # raise x to the y power",options:["Yes","No"],correct:1,explanation:"The # is NOT optional. Without it, the text would be interpreted as code and cause a SyntaxError. Every comment line needs #."},
  {question:"Line 06: comment = '#Return the value'. Will this string be interpreted as a comment?",code:"01 # The calc_power function calculates exponents\n02 # x is the base\n03 # y is the exponent\n04 # The value of x raised to the y power is returned\n05 def calc_power(x, y):\n06     comment = \"#Return the value\"\n07     return x**y  # raise x to the y power",options:["Yes","No"],correct:1,explanation:"A # inside a string literal is just a character, not a comment marker. The string is assigned to the variable normally."},
  {question:"Line 07 contains an inline comment. True?",code:"01 # The calc_power function calculates exponents\n02 # x is the base\n03 # y is the exponent\n04 # The value of x raised to the y power is returned\n05 def calc_power(x, y):\n06     comment = \"#Return the value\"\n07     return x**y  # raise x to the y power",options:["Yes","No"],correct:0,explanation:"The # after the code on line 07 starts an inline comment. Everything after # on that line is ignored by Python."},
  {question:"A try statement can have one or more except clauses. True or False?",options:["True","False"],correct:0,explanation:"A try block can handle multiple exception types with separate except clauses. This is valid and commonly used."},
  {question:"A try statement can have a finally clause without an except clause. True or False?",options:["True","False"],correct:0,explanation:"try...finally is valid Python. The finally block runs regardless of whether an exception occurred, even without except."},
  {question:"A try statement can have both a finally clause and an except clause. True or False?",options:["True","False"],correct:0,explanation:"try...except...finally is valid. The except handles errors and finally always runs for cleanup."},
  {question:"A try statement can have one or more finally clauses. True or False?",options:["True","False"],correct:1,explanation:"Only ONE finally clause is allowed per try statement. Multiple finally clauses would cause a SyntaxError."},
  {question:"To meet requirements (default points=1), line 01 must be changed. True?",code:"01 def increment_score(score, bonus, points):\n02     if bonus == True:\n03         points = points * 2\n04     score = score + points\n05     return score\n06 points = 5\n07 score = 10\n08 new_score = increment_score(score, True, points)",options:["Yes","No"],correct:0,explanation:"Setting points=1 as a default parameter means if no value is passed for points, it defaults to 1, meeting the requirement."},
  {question:"Once any parameter has a default value, parameters to the right must also have defaults. True?",code:"01 def increment_score(score, bonus, points):\n02     if bonus == True:\n03         points = points * 2\n04     score = score + points\n05     return score",options:["Yes","No"],correct:0,explanation:"Python requires that all parameters after the first defaulted one also have defaults. You cannot have def f(a, b=1, c) — c needs a default too."},
  {question:"If the function is called with only two parameters, the third parameter will be None. True?",code:"01 def increment_score(score, bonus, points=1):\n02     if bonus == True:\n03         points = points * 2\n04     score = score + points\n05     return score",options:["Yes","No"],correct:1,explanation:"If points has a default value of 1, calling with two parameters gives points=1, not None. None only applies if the default is explicitly None."},
  {question:"Will print at line 04 only execute if the two numbers are equal in value?",code:"01 num1 = eval(input(\"Please enter the first number: \"))\n02 num2 = eval(input(\"Please enter the second number: \"))\n03 if num1 == num2:\n04     print(\"The two numbers are equal.\")\n05 if num1 <= num2:\n06     print(\"Number 1 is less than number 2.\")\n07 if num1 > num2:\n08     print(\"Number 1 is greater than number 2.\")\n09 if num2 = num1:\n10     print(\"The two numbers are the same.\")",options:["Yes","No"],correct:0,explanation:"The == operator checks value equality. The print statement only executes when num1 and num2 have the same value."},
  {question:"Will print at line 06 only execute if num1 is less than num2?",code:"01 num1 = eval(input(\"Please enter the first number: \"))\n02 num2 = eval(input(\"Please enter the second number: \"))\n03 if num1 == num2:\n04     print(\"The two numbers are equal.\")\n05 if num1 <= num2:\n06     print(\"Number 1 is less than number 2.\")\n07 if num1 > num2:\n08     print(\"Number 1 is greater than number 2.\")\n09 if num2 = num1:\n10     print(\"The two numbers are the same.\")",options:["Yes","No"],correct:1,explanation:"<= means less than OR equal to. It also prints when num1 equals num2, not only when strictly less than."},
  {question:"Will print at line 08 only execute if num1 is greater than num2?",code:"01 num1 = eval(input(\"Please enter the first number: \"))\n02 num2 = eval(input(\"Please enter the second number: \"))\n03 if num1 == num2:\n04     print(\"The two numbers are equal.\")\n05 if num1 <= num2:\n06     print(\"Number 1 is less than number 2.\")\n07 if num1 > num2:\n08     print(\"Number 1 is greater than number 2.\")\n09 if num2 = num1:\n10     print(\"The two numbers are the same.\")",options:["Yes","No"],correct:0,explanation:"> is strictly greater than. The print only executes when num1 is larger than num2, which is correct."},
  {question:"Is the statement at line 09 an invalid comparison?",code:"01 num1 = eval(input(\"Please enter the first number: \"))\n02 num2 = eval(input(\"Please enter the second number: \"))\n03 if num1 == num2:\n04     print(\"The two numbers are equal.\")\n05 if num1 <= num2:\n06     print(\"Number 1 is less than number 2.\")\n07 if num1 > num2:\n08     print(\"Number 1 is greater than number 2.\")\n09 if num2 = num1:\n10     print(\"The two numbers are the same.\")",options:["Yes","No"],correct:0,explanation:"Single = is assignment, not comparison. In an if statement, = causes a SyntaxError. It should be == for comparison."},
  {question:"What is the result of: 0 or 5?",options:["True","False","5","None"],correct:2,explanation:"Python's 'or' returns the first truthy value. 0 is falsy, so it evaluates and returns the second operand: 5."},
  {question:"What is the result of: bool(0)?",options:["True","False","0","None"],correct:1,explanation:"0 is a falsy value in Python. bool(0) converts it to the boolean False."},
  {question:"What is the result of: None is None?",options:["True","False","None","Error"],correct:0,explanation:"There is only one None singleton in Python. 'is' checks identity, and None is always the same object, so True."},
  {question:"What is the result of: -5 < 0 < 5?",options:["True","False","Error","None"],correct:0,explanation:"Python supports chained comparisons. -5<0 is True and 0<5 is True, so the entire chain evaluates to True."},
  {question:"Guess game: chance=1, needs 3 guesses, stop if correct. Which code for line 05 (the loop)?",options:["while chance <= 3:","while chance < 3:","while chance < 3","while chance <= 3"],correct:0,explanation:"Starting at chance=1, 'while chance <= 3:' allows 3 iterations (1,2,3). The colon is required for valid Python syntax."},
  {question:"In the guess game, what goes at line 13 (after correct guess in else block)?",options:["break","pass","chance += 1","chance = 2"],correct:0,explanation:"'break' exits the while loop immediately when the correct number is guessed, preventing further unnecessary guesses."},
  {question:"In the guess game, what goes at line 14 (incrementing attempts)?",options:["break","pass","chance += 1","chance = 2"],correct:2,explanation:"chance += 1 increments the counter after each guess attempt, eventually causing the while condition to become False after 3 tries."},
  {question:"Grade converter: first condition for 90-100 getting 'A'. Which code?",options:["if grade <= 90:","if grade >= 90:","elif grade > 90:","elif grade >= 90:"],correct:1,explanation:"The first condition uses 'if' (not elif) and checks grade >= 90 to assign letter grade 'A' for scores 90-100."},
  {question:"Grade converter: condition for 80-89 getting 'B'. Which code?",options:["if grade > 80:","if grade >= 80:","elif grade > 80:","elif grade >= 80:"],correct:3,explanation:"After the first 'if', subsequent conditions use 'elif'. grade >= 80 catches 80-89 (since 90+ was already handled)."},
  {question:"Speed calculator needs precise output. What type for distance input?",options:["int","float","str"],correct:1,explanation:"float() gives the most precise result for division calculations. int would lose decimal precision needed for velocity."},
  {question:"Speed calculator needs precise output. What type for time input?",options:["int","str","float"],correct:2,explanation:"float() preserves decimal precision in the time measurement, ensuring the velocity calculation is as precise as possible."},
  {question:"DVD rental: if returned after 8pm, charge extra day. ontime=input().lower(). Which condition adds a day?",options:['if ontime != "n":','if ontime == "n":','if ontime == "y":'],correct:1,explanation:"If ontime == 'n' (not returned before 8pm), add an extra day. The .lower() ensures case-insensitive comparison."},
  {question:"DVD rental: Sunday gets 30% off. Which condition checks for Sunday?",options:['if day_rented == "Sunday":','if day_rented >= "Sunday":','if day_rented is "Sunday":'],correct:0,explanation:"== is the correct equality operator for string comparison. 'is' checks identity (not value), and >= makes no sense for strings here."},
  {question:"DVD rental: Thursday gets 50% off. Which condition for Thursday?",options:['elif day_rented == "Thursday":','elif day_rented <= "Thursday":','elif day_rented is "Thursday":'],correct:0,explanation:"elif continues the if/elif chain, and == correctly compares the string value. .capitalize() ensures proper case matching."},
  {question:"Function update_score: receives current score and value, adds value, returns new score. What starts the definition?",options:["update_score","def update_score","return update_score"],correct:1,explanation:"Functions in Python are defined with the 'def' keyword followed by the function name."},
  {question:"update_score receives current score and value. What are the parameters?",options:["(current, value):","():","(current, value)","()"],correct:0,explanation:"The function needs two parameters (current and value) with a colon to start the function body."},
  {question:"update_score must return the new score. Which statement?",options:["pass current","return current","return","pass"],correct:1,explanation:"'return current' sends back the updated score value (after current += value) to the caller."},
  {question:"Survey program: rating must accept float input. Which code?",options:['print("Enter next rating (1-5), -1 for done")','float(input("Enter next rating (1-5), -1 for done"))','input("Enter next rating (1-5), -1 for done")','input "Enter next rating (1-5), -1 for done"'],correct:1,explanation:"float(input(...)) converts the user's string input to a floating-point number for mathematical operations."},
  {question:"To print average rounded to 2 decimal places, which format code?",options:["format(average, '.2f')","format(average, '.2d')","{average, '.2f'}","format.average.{2d}"],correct:0,explanation:"format(average, '.2f') formats the float to 2 decimal places. '.2f' means 2 digits after the decimal point as float."},
];

let currentQuestion=0,score=0,answered=[],activeQuestions=[],displayMode='one',hintsEnabled=true,selectedOptions=[];
function setMode(m){displayMode=m;document.getElementById('modeOneBtn').classList.toggle('active',m==='one');document.getElementById('modeAllBtn').classList.toggle('active',m==='all');}
function shuffleArray(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function isMultiSelect(q){return Array.isArray(q.correct);}
function isCorrectAnswer(q,i){return Array.isArray(q.correct)?q.correct.includes(i):i===q.correct;}
function startQuiz(shuffle){hintsEnabled=document.getElementById('hintToggle').checked;activeQuestions=[...questions];if(shuffle)shuffleArray(activeQuestions);answered=new Array(activeQuestions.length).fill(null);currentQuestion=0;score=0;document.getElementById('startScreen').classList.add('hidden');document.getElementById('resultsContainer').classList.add('hidden');if(displayMode==='one'){document.getElementById('quizContainer').classList.remove('hidden');document.getElementById('allQuestionsContainer').classList.add('hidden');loadQuestion();}else{document.getElementById('quizContainer').classList.add('hidden');document.getElementById('allQuestionsContainer').classList.remove('hidden');loadAllQuestions();}}

function loadQuestion(){const q=activeQuestions[currentQuestion];document.getElementById('questionNumber').textContent=`Question ${currentQuestion+1}`;document.getElementById('questionText').textContent=q.question;document.getElementById('progressText').textContent=`Question ${currentQuestion+1} of ${activeQuestions.length}`;document.getElementById('progressFill').style.width=`${((currentQuestion+1)/activeQuestions.length)*100}%`;const cb=document.getElementById('codeBlock');if(q.code){cb.textContent=q.code;cb.classList.add('visible');}else{cb.classList.remove('visible');cb.textContent='';}const oc=document.getElementById('optionsContainer');oc.innerHTML='';if(isMultiSelect(q)&&answered[currentQuestion]===null){const h=document.createElement('p');h.className='multi-hint';h.textContent=`(Select ${q.correct.length} answers)`;oc.appendChild(h);}
q.options.forEach((opt,idx)=>{const btn=document.createElement('button');btn.className='option-btn';btn.textContent=opt;btn.onclick=()=>selectAnswer(idx);if(answered[currentQuestion]!==null){btn.classList.add('disabled');if(isCorrectAnswer(q,idx))btn.classList.add('show-correct');const ua=Array.isArray(answered[currentQuestion])?answered[currentQuestion]:[answered[currentQuestion]];if(ua.includes(idx)&&!isCorrectAnswer(q,idx))btn.classList.add('incorrect');}if(isMultiSelect(q)&&answered[currentQuestion]===null&&selectedOptions.includes(idx))btn.classList.add('selected');oc.appendChild(btn);});
const fb=document.getElementById('feedback'),ex=document.getElementById('explanation');if(answered[currentQuestion]!==null){fb.style.display='block';const ua=Array.isArray(answered[currentQuestion])?answered[currentQuestion]:[answered[currentQuestion]];let ok=isMultiSelect(q)?q.correct.every(c=>ua.includes(c))&&ua.length===q.correct.length:ua[0]===q.correct;if(ok){fb.className='feedback correct';fb.textContent='\u2713 Correct!';}else{fb.className='feedback incorrect';const ct=isMultiSelect(q)?q.correct.map(c=>q.options[c]).join(' & '):q.options[q.correct];fb.textContent=`\u2717 Incorrect. Correct: ${ct}`;}if(hintsEnabled){ex.style.display='block';ex.textContent=q.explanation;}else{ex.style.display='none';}}else{fb.style.display='none';ex.style.display='none';}
document.getElementById('prevBtn').disabled=currentQuestion===0;document.getElementById('nextBtn').disabled=answered[currentQuestion]===null;document.getElementById('nextBtn').textContent=(currentQuestion===activeQuestions.length-1&&answered[currentQuestion]!==null)?'See Results \u2192':'Next \u2192';}

function selectAnswer(idx){if(answered[currentQuestion]!==null)return;const q=activeQuestions[currentQuestion];if(isMultiSelect(q)){if(selectedOptions.includes(idx))selectedOptions=selectedOptions.filter(i=>i!==idx);else selectedOptions.push(idx);if(selectedOptions.length===q.correct.length){answered[currentQuestion]=[...selectedOptions];if(q.correct.every(c=>selectedOptions.includes(c)))score++;selectedOptions=[];loadQuestion();}else loadQuestion();}else{answered[currentQuestion]=idx;if(idx===q.correct)score++;loadQuestion();}}
function nextQuestion(){if(currentQuestion<activeQuestions.length-1){currentQuestion++;loadQuestion();}else showResults();}
function prevQuestion(){if(currentQuestion>0){currentQuestion--;loadQuestion();}}
let allSelectedOptions={};
function loadAllQuestions(){const c=document.getElementById('allQuestionsList');c.innerHTML='';allSelectedOptions={};activeQuestions.forEach((q,qi)=>{const card=document.createElement('div');card.className='all-question-card';card.id=`allQ${qi}`;let hint=isMultiSelect(q)?`<p class="multi-hint">(Select ${q.correct.length} answers)</p>`:'';if(isMultiSelect(q))allSelectedOptions[qi]=[];let code=q.code?`<div class="code-block visible">${q.code}</div>`:'';let opts='';q.options.forEach((o,oi)=>{opts+=`<button class="option-btn" onclick="selectAllAnswer(${qi},${oi})" id="allQ${qi}O${oi}">${o}</button>`;});card.innerHTML=`<h2 class="question-number">Question ${qi+1}</h2><p class="question-text">${q.question}</p>${code}${hint}<div class="options">${opts}</div><div class="feedback" id="allFb${qi}"></div><div class="explanation" id="allEx${qi}"></div>`;c.appendChild(card);});updateAllProgress();}

function selectAllAnswer(qi,oi){if(answered[qi]!==null)return;const q=activeQuestions[qi];if(isMultiSelect(q)){const s=allSelectedOptions[qi],idx=s.indexOf(oi);if(idx>-1)s.splice(idx,1);else s.push(oi);q.options.forEach((_,i)=>{document.getElementById(`allQ${qi}O${i}`).classList.toggle('selected',s.includes(i));});if(s.length===q.correct.length){answered[qi]=[...s];if(q.correct.every(c=>s.includes(c)))score++;showAllFb(qi);}}else{answered[qi]=oi;if(oi===q.correct)score++;showAllFb(qi);}updateAllProgress();}
function showAllFb(qi){const q=activeQuestions[qi],card=document.getElementById(`allQ${qi}`),fb=document.getElementById(`allFb${qi}`),ex=document.getElementById(`allEx${qi}`);q.options.forEach((_,i)=>{const b=document.getElementById(`allQ${qi}O${i}`);b.classList.add('disabled');b.classList.remove('selected');if(isCorrectAnswer(q,i))b.classList.add('show-correct');const ua=Array.isArray(answered[qi])?answered[qi]:[answered[qi]];if(ua.includes(i)&&!isCorrectAnswer(q,i))b.classList.add('incorrect');});const ua=Array.isArray(answered[qi])?answered[qi]:[answered[qi]];let ok=isMultiSelect(q)?q.correct.every(c=>ua.includes(c))&&ua.length===q.correct.length:ua[0]===q.correct;fb.style.display='block';if(ok){fb.className='feedback correct';fb.textContent='\u2713 Correct!';card.classList.add('answered-correct');}else{fb.className='feedback incorrect';const ct=isMultiSelect(q)?q.correct.map(c=>q.options[c]).join(' & '):q.options[q.correct];fb.textContent=`\u2717 Incorrect. Correct: ${ct}`;card.classList.add('answered-incorrect');}if(hintsEnabled){ex.style.display='block';ex.textContent=q.explanation;}}
function updateAllProgress(){const c=answered.filter(a=>a!==null).length;document.getElementById('allProgressText').textContent=`${c} of ${activeQuestions.length} answered`;document.getElementById('submitAllBtn').disabled=c<activeQuestions.length;}
function submitAll(){document.getElementById('allQuestionsContainer').classList.add('hidden');showResults();}

function showResults(){document.getElementById('quizContainer').classList.add('hidden');document.getElementById('resultsContainer').classList.remove('hidden');const pct=Math.round((score/activeQuestions.length)*100);document.getElementById('scoreDisplay').textContent=`${score} / ${activeQuestions.length} (${pct}%)`;let msg=pct>=70?'You passed! Minimum score to pass is 70%.':pct>=50?'Almost there! Review missed topics and try again.':'Keep studying! Focus on areas where you struggled.';if(pct===100)msg='Perfect score! You mastered Introduction to Programming Using Python!';document.getElementById('scoreMessage').textContent=msg;
const sl=document.getElementById('summaryList');sl.innerHTML='';const fd=document.createElement('div');fd.className='summary-filter';fd.innerHTML=`<button class="filter-btn active" onclick="filterSummary('all',this)">All (${activeQuestions.length})</button><button class="filter-btn" onclick="filterSummary('correct',this)">\u2713 Correct (${score})</button><button class="filter-btn" onclick="filterSummary('incorrect',this)">\u2717 Incorrect (${activeQuestions.length-score})</button>`;sl.appendChild(fd);
activeQuestions.forEach((q,i)=>{const ua=Array.isArray(answered[i])?answered[i]:[answered[i]];let ok=isMultiSelect(q)?q.correct.every(c=>ua.includes(c))&&ua.length===q.correct.length:ua[0]===q.correct;const item=document.createElement('div');item.className=`summary-item ${ok?'correct':'incorrect'}`;item.dataset.result=ok?'correct':'incorrect';const uaT=ua.map(a=>q.options[a]).join(' & '),caT=isMultiSelect(q)?q.correct.map(c=>q.options[c]).join(' & '):q.options[q.correct];let aH=ok?`Your answer: <span>${uaT}</span>`:`Your answer: ${uaT} | Correct: <span>${caT}</span>`;item.innerHTML=`<div class="summary-status">${ok?'\u2713 Correct':'\u2717 Incorrect'}</div><div class="summary-question">${i+1}. ${q.question.substring(0,120)}${q.question.length>120?'...':''}</div><div class="summary-answer">${aH}</div><div class="summary-explanation">${q.explanation}</div>`;sl.appendChild(item);});}
function filterSummary(t,btn){document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.summary-item').forEach(item=>{item.style.display=(t==='all'||item.dataset.result===t)?'block':'none';});}
function restartQuiz(){document.getElementById('resultsContainer').classList.add('hidden');document.getElementById('quizContainer').classList.add('hidden');document.getElementById('allQuestionsContainer').classList.add('hidden');document.getElementById('startScreen').classList.remove('hidden');}
